name: Deploy Todo App to AKS via ArgoCD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Navigate to the Helm chart directory
      run: |
        cd todo-app-chart
        ls

    - name: Update values.yaml file and commit if necessary
      run: |
        cd todo-app-chart
        sed -i 's/replicas: .*/replicas: 4/' values.yaml  # Modify replica count
        git diff --exit-code values.yaml || ( \
          git config --global user.name 'GitHub Actions' && \
          git config --global user.email 'actions@github.com' && \
          git add -A && \
          git commit -m "Update values.yaml" && \
          git push \
        )
